### ISSUE TITLE
GPipe is not in stackage nightly.

### ISSUE THREAD

**Issue by DevJac** [tobbebex/GPipe-Core#52]
I tried changing the version bounds in the Cabal file, but I couldn't get GPipe to compile with GHC 8.2.

Is this a known issue?

**Comment by DevJac** [comment]
If I checkout master and do `stack build` I get the following error:

```
GPipe-2.2.1: build (lib)
Preprocessing library GPipe-2.2.1...
[ 3 of 28] Compiling Graphics.GPipe.Internal.Format ( src/Graphics/GPipe/Internal/Format.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Graphics/GPipe/Internal/Format.o )

/home/buttons/Code/haskell/game/GPipe-Core/GPipe-Core/src/Graphics/GPipe/Internal/Format.hs:402:10: error:
    • No instance for (TextureFormat Stencil)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘StencilRenderable Stencil’
```

I've tried building a few of the recent commits and can't get any of them to build with stack. Is this expected? Should I be able to compile the master branch in it's current state?

**Comment by DevJac** [comment]
Here are some recent commits:

```
X 81fc5e6 - (6 weeks ago) Removing TextureFroamt on Stencil. Fixes #45 - tobbebex (HEAD -> master, origin/master, origin/HEAD)
* 2982c53 - (4 months ago) Fixing compilation errors + bumping changelog for 2.2.1 - tobbebex
X   5a1aabf - (4 months ago) Merge branch 'master' of https://github.com/tobbebex/GPipe-Core - tobbebex
|\  
| * cc192a6 - (5 months ago) Bumping version to 2.2.1 after 2.2 release - tobbebex
| * b962fde - (5 months ago) Update CHANGELOG.md - tobbebex
X | dda0c58 - (4 months ago) Fixing #41 and #42 - tobbebex
|/  
* 32ef0ec - (5 months ago) Renaming getWindowSize to getFrameBufferSize. Fixes #35 - tobbebex
```
The ones marked with `X` are will not build when I run `stack build`.

Just sharing the results of my experiments. I realize that not every project expects that every commit in the can build.

**Comment by DevJac** [comment]
Good news. Commit `2982c53` works with GHC 8.2. I just had to bump the version bounds for `base` to allow `4.10`.

I will submit a PR.

Also, it would be nice if we could get GPipe back into stackage nightly.

**Comment by tobbebex** [comment]
GPipe is readded to stackage in fpco/stackage/pull/2889
